/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary)",
        "on-primary": "var(--color-on-primary)",
        secondary: "var(--color-secondary)",
        "on-secondary": "var(--color-on-secondary)",
        surface: "var(--color-surface)",
        "on-surface": "var(--color-on-surface)",
        background: "var(--color-background)",
        "on-background": "var(--color-on-background)",
        outline: "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        error: "var(--color-error)",
        "on-error": "var(--color-on-error)",
        "error-container": "var(--color-error-container)",
        "on-error-container": "var(--color-on-error-container)",
        success: "#10b981",
        "on-success": "#ffffff",
        "success-container": "#dcfce7",
        "on-success-container": "#065f46",
        "primary-container": "var(--color-surface-container-high)",
        "on-primary-container": "var(--color-on-surface)",
        "surface-variant": "var(--color-surface-container)",
      },
      borderRadius: {
        "sm": "16px",
        "DEFAULT": "16px",
        "md": "16px",
        "lg": "16px",
        "xl": "16px",
        "2xl": "16px",
        "pebble": "16px",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "12px",
        "lg": "16px",
        "xl": "24px",
        "2xl": "32px",
        "3xl": "48px",
        "4xl": "64px",
        "unit": "8px",
        "pebble": "24px",
        "container-padding": "24px",
        "max-width": "1440px",
        "navbar-h": "72px"
      },
      fontFamily: {
        "body-sm": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "label-bold": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "display": ["Geist", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["13px", { "lineHeight": "1.55", "letterSpacing": "-0.005em", "fontWeight": "400" }],
        "body-md": ["15px", { "lineHeight": "1.6", "letterSpacing": "-0.005em", "fontWeight": "400" }],
        "body-lg": ["17px", { "lineHeight": "1.55", "letterSpacing": "-0.015em", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "1.4", "letterSpacing": "0.04em", "fontWeight": "500" }],
        "label-bold": ["12px", { "lineHeight": "1.4", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "headline-sm": ["18px", { "lineHeight": "1.35", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-md": ["22px", { "lineHeight": "1.3", "letterSpacing": "-0.025em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.03em", "fontWeight": "600" }],
        "display": ["48px", { "lineHeight": "1.05", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "display-lg": ["72px", { "lineHeight": "1", "letterSpacing": "-0.05em", "fontWeight": "700" }],
      },
      maxWidth: {
        "max-width": "1440px",
      },
      boxShadow: {
        "premium": "0 1px 3px rgba(0,0,0,0.04), 0 4px 12px rgba(0,0,0,0.04)",
        "elevated": "0 4px 24px rgba(0,0,0,0.06), 0 1px 4px rgba(0,0,0,0.04)",
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};